version: '3.8'

services:
  agent-platform:
    build:
      context: .
      dockerfile: Dockerfile
    image: agent-platform:latest
    container_name: agent-platform
    ports:
      - "8501:8501"  # Streamlit UI
      - "8000:8000"  # FastAPI
    volumes:
      - ./data:/app/data  # Persist data
      - ./.env:/app/.env  # Environment variables
      - models_cache:/app/models  # Persist downloaded models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - USE_LOCAL_MODELS=true
      - LOCAL_MODELS_DIR=/app/models
      - DOWNLOAD_MODELS=true  # Set to false after first run if models are persisted
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Longer start period to account for model downloads

  # Optional: Include a database service if needed
  # db:
  #   image: postgres:15-alpine
  #   container_name: agent-platform-db
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=agent_platform
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

  # Optional: Include a vector database service if needed
  # weaviate:
  #   image: cr.weaviate.io/semitechnologies/weaviate:1.23.0
  #   container_name: agent-platform-weaviate
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - QUERY_DEFAULTS_LIMIT=20
  #     - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
  #     - PERSISTENCE_DATA_PATH=/var/lib/weaviate
  #   volumes:
  #     - weaviate_data:/var/lib/weaviate
  #   restart: unless-stopped

  # Optional: Include a vector database for embeddings
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: agent-platform-chromadb
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
    restart: unless-stopped

volumes:
  models_cache:  # Persistent volume for downloaded models
  chroma_data:  # Persistent volume for ChromaDB
  postgres_data:
  weaviate_data:
