version: '3.8'

services:
  agent-forge:
    build: .
    container_name: agent-forge
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # You can define default environment variables here
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - EMBEDDING_MODEL=text-embedding-ada-002
    restart: unless-stopped

  # Uncomment to run settings UI separately
  # settings-ui:
  #   build: .
  #   container_name: agent-forge-settings
  #   ports:
  #     - "8502:8501"
  #   volumes:
  #     - .:/app
  #     - ./.env:/app/.env
  #   command: streamlit run start_server.py -- --settings
  #   environment:
  #     - PYTHONPATH=/app
  #     - PYTHONUNBUFFERED=1
  #   restart: unless-stopped
